name: CI/CD Production Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to AWS Server and Deploy Containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key:  ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Update system packages and install Docker if it doesn't exist yet
            sudo apt-get update -y
            if ! command -v docker &> /dev/null
            then
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -aG docker ubuntu
            fi

            # 2. Authenticate the server session with Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # 3. Stop and wipe any stale container processes running on our production port
            sudo docker stop devops-app-prod || true
            sudo docker rm devops-app-prod || true

            # 4. Pull the fresh image blueprint we just pushed to the registry
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

            # 5. Spin up the application container live on the internet!
            sudo docker run -d --name devops-app-prod -p 5000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

            # 6. Spin up Node Exporter to broadcast server metrics on port 9100
            sudo docker stop node-exporter || true
            sudo docker rm node-exporter || true
            sudo docker run -d --name node-exporter --net="host" --pid="host" -v "/:/host:ro,rslave" prom/node-exporter:v1.6.0 --path.rootfs=/host
